# Generated by Django 4.1 on 2024-07-25 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_alter_profile_profileimg"),
    ]

    operations = [
        migrations.RenameModel(old_name="profile", new_name="UserProfile",),
    ]
