# Generated by Django 4.1 on 2024-07-25 11:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_rename_profile_userprofile"),
    ]

    operations = [
        migrations.RenameModel(old_name="UserProfile", new_name="Profile",),
    ]
